### ISSUE TITLE
Add reference to specialize tactic?

### ISSUE THREAD

**Issue by bmsherman** [jldodds/coq-lean-cheatsheet#5]
I made a version of the `specialize` tactic for Lean:

https://github.com/GaloisInc/lean-protocol-support/blob/c5242f551c7a177d5d3335d5bb69abc962c1d944/galois/tactic.lean

Perhaps this would be useful to refer to in the cheatsheet in some capacity.

**Comment by jldodds** [comment]
Can you just commit it here as well? Then we'll reference it
